# Generated by Django 4.2 on 2023-08-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_product_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_measurement_unit',
            field=models.CharField(blank=True, choices=[('KG', 'KG'), ('ML', 'ML'), ('L', 'L'), ('None', None)], max_length=50, null=True),
        ),
    ]
